import { MedicineItem, AlertItem, StockLogEntry, ImportSyncBatch } from './types';

export const INITIAL_MEDICINES: MedicineItem[] = [
  {
    id: 'med-01',
    sku: 'SKU-AMOX-500',
    name: 'Amoxicillin Trihydrate',
    category: 'Antibiotics',
    dosage: '500mg Capsules',
    currentStock: 480,
    minThreshold: 1200,
    unit: 'Capsules',
    batchNumber: 'AMX-2024-88A',
    expiryDate: '2027-04-15',
    consumptionVelocity: 145,
    daysRemaining: 3.3,
    riskScore: 94,
    predictedStockoutDate: '3 Days (Sept 25)',
    status: 'Critical Risk',
    leadTimeDays: 7,
    coldChainRequired: false,
    dvdmsMapped: true,
  },
  {
    id: 'med-02',
    sku: 'SKU-CEFT-1000',
    name: 'Ceftriaxone Sodium Inj',
    category: 'Antibiotics',
    dosage: '1g IV/IM Vial',
    currentStock: 190,
    minThreshold: 800,
    unit: 'Vials',
    batchNumber: 'CFT-9021-B',
    expiryDate: '2026-11-30',
    consumptionVelocity: 62,
    daysRemaining: 3.1,
    riskScore: 92,
    predictedStockoutDate: '3 Days (Sept 25)',
    status: 'Critical Risk',
    leadTimeDays: 5,
    coldChainRequired: false,
    dvdmsMapped: true,
  },
  {
    id: 'med-03',
    sku: 'SKU-EPIN-01',
    name: 'Epinephrine Injection',
    category: 'Emergency & Critical',
    dosage: '1mg/mL Ampoule (1:1000)',
    currentStock: 85,
    minThreshold: 250,
    unit: 'Ampoules',
    batchNumber: 'EPN-0044-K',
    expiryDate: '2027-01-20',
    consumptionVelocity: 18,
    daysRemaining: 4.7,
    riskScore: 89,
    predictedStockoutDate: '4 Days (Sept 26)',
    status: 'Critical Risk',
    leadTimeDays: 6,
    coldChainRequired: true,
    dvdmsMapped: true,
  },
  {
    id: 'med-04',
    sku: 'SKU-METF-500',
    name: 'Metformin Hydrochloride',
    category: 'Endocrine',
    dosage: '500mg Tablets',
    currentStock: 2100,
    minThreshold: 3000,
    unit: 'Tablets',
    batchNumber: 'MTF-2024-119',
    expiryDate: '2028-02-14',
    consumptionVelocity: 280,
    daysRemaining: 7.5,
    riskScore: 68,
    predictedStockoutDate: '7 Days (Sept 29)',
    status: 'Low Stock',
    leadTimeDays: 4,
    coldChainRequired: false,
    dvdmsMapped: true,
  },
  {
    id: 'med-05',
    sku: 'SKU-ATOR-20',
    name: 'Atorvastatin Calcium',
    category: 'Cardiovascular',
    dosage: '20mg Film-coated',
    currentStock: 1650,
    minThreshold: 2400,
    unit: 'Tablets',
    batchNumber: 'ATV-7712-C',
    expiryDate: '2027-09-08',
    consumptionVelocity: 195,
    daysRemaining: 8.5,
    riskScore: 61,
    predictedStockoutDate: '8 Days (Sept 30)',
    status: 'Low Stock',
    leadTimeDays: 6,
    coldChainRequired: false,
    dvdmsMapped: true,
  },
  {
    id: 'med-06',
    sku: 'SKU-SALB-100',
    name: 'Salbutamol Sulfate Inhaler',
    category: 'Respiratory',
    dosage: '100mcg/dose (200 Doses)',
    currentStock: 120,
    minThreshold: 350,
    unit: 'Canisters',
    batchNumber: 'SLB-8820-D',
    expiryDate: '2027-06-30',
    consumptionVelocity: 24,
    daysRemaining: 5.0,
    riskScore: 84,
    predictedStockoutDate: '5 Days (Sept 27)',
    status: 'Critical Risk',
    leadTimeDays: 8,
    coldChainRequired: false,
    dvdmsMapped: true,
  },
  {
    id: 'med-07',
    sku: 'SKU-PARA-650',
    name: 'Paracetamol Tablets',
    category: 'Analgesics',
    dosage: '650mg Oral Tablets',
    currentStock: 14500,
    minThreshold: 8000,
    unit: 'Tablets',
    batchNumber: 'PCM-1109-Z',
    expiryDate: '2028-10-15',
    consumptionVelocity: 720,
    daysRemaining: 20.1,
    riskScore: 18,
    predictedStockoutDate: 'Stable (> 20 days)',
    status: 'In Stock',
    leadTimeDays: 3,
    coldChainRequired: false,
    dvdmsMapped: true,
  },
  {
    id: 'med-08',
    sku: 'SKU-INS-GLAR',
    name: 'Insulin Glargine Pen',
    category: 'Endocrine',
    dosage: '100 units/mL (3mL Cartridge)',
    currentStock: 74,
    minThreshold: 150,
    unit: 'Pens',
    batchNumber: 'INS-0992-G',
    expiryDate: '2026-10-12',
    consumptionVelocity: 14,
    daysRemaining: 5.2,
    riskScore: 79,
    predictedStockoutDate: '5 Days (Sept 27)',
    status: 'Low Stock',
    leadTimeDays: 5,
    coldChainRequired: true,
    dvdmsMapped: true,
  },
  {
    id: 'med-09',
    sku: 'SKU-AZITH-500',
    name: 'Azithromycin Dihydrate',
    category: 'Antibiotics',
    dosage: '500mg Tablets',
    currentStock: 820,
    minThreshold: 600,
    unit: 'Tablets',
    batchNumber: 'AZT-4431-A',
    expiryDate: '2027-08-19',
    consumptionVelocity: 65,
    daysRemaining: 12.6,
    riskScore: 32,
    predictedStockoutDate: '12 Days (Oct 4)',
    status: 'In Stock',
    leadTimeDays: 4,
    coldChainRequired: false,
    dvdmsMapped: true,
  },
  {
    id: 'med-10',
    sku: 'SKU-FURO-40',
    name: 'Furosemide Injection',
    category: 'Cardiovascular',
    dosage: '20mg/2mL Ampoule',
    currentStock: 340,
    minThreshold: 450,
    unit: 'Ampoules',
    batchNumber: 'FRM-3120-Q',
    expiryDate: '2027-03-01',
    consumptionVelocity: 35,
    daysRemaining: 9.7,
    riskScore: 54,
    predictedStockoutDate: '9 Days (Oct 1)',
    status: 'Low Stock',
    leadTimeDays: 4,
    coldChainRequired: false,
    dvdmsMapped: true,
  }
];

export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'alt-01',
    severity: 'critical',
    title: 'Severe Stockout Imminent: Amoxicillin 500mg',
    message: 'Depletion estimated within 3.3 days due to 48% spike in District 04 pediatric prescriptions.',
    medicineSku: 'SKU-AMOX-500',
    medicineName: 'Amoxicillin Trihydrate 500mg',
    timestamp: '12 mins ago',
    acknowledged: false,
    actionRequired: 'Initiate Emergency Restock Order to State Depot',
  },
  {
    id: 'alt-02',
    severity: 'critical',
    title: 'Cold-Chain Warning: Insulin Glargine Pen',
    message: 'Refrigerator Unit 02 recorded transient temperature excursion to 9.2°C (permitted range 2-8°C).',
    medicineSku: 'SKU-INS-GLAR',
    medicineName: 'Insulin Glargine Pen 100u/mL',
    timestamp: '34 mins ago',
    acknowledged: false,
    actionRequired: 'Verify Cold-Chain Sensor & Inspect Batch INS-0992-G',
  },
  {
    id: 'alt-03',
    severity: 'critical',
    title: 'Emergency Stock Critical: Epinephrine 1mg/mL',
    message: 'Current stock represents only 4.7 days reserve against WHO mandatory emergency quota.',
    medicineSku: 'SKU-EPIN-01',
    medicineName: 'Epinephrine Injection 1mg/mL',
    timestamp: '1 hour ago',
    acknowledged: false,
    actionRequired: 'Trigger Regional Rebalance from District 02 Depot',
  },
  {
    id: 'alt-04',
    severity: 'warning',
    title: 'Predicted Surge in Respiratory Medications',
    message: 'Seasonal epidemiological model flags 35% incoming demand surge for Salbutamol canisters.',
    medicineSku: 'SKU-SALB-100',
    medicineName: 'Salbutamol Sulfate Inhaler',
    timestamp: '2 hours ago',
    acknowledged: false,
    actionRequired: 'Adjust safety threshold +250 units',
  },
  {
    id: 'alt-05',
    severity: 'warning',
    title: 'e-Aushadhi Batch Mapping Discrepancy',
    message: '14 SKUs in latest state upload had minor packaging variant mismatches during auto-reconciliation.',
    timestamp: '3 hours ago',
    acknowledged: true,
    actionRequired: 'Review Data Reconciliation ledger in Data Import hub',
  },
  {
    id: 'alt-06',
    severity: 'info',
    title: 'Automated CDSCO Compliance Dossier Generated',
    message: 'Weekly Schedule H1 drug surveillance report successfully generated and archived for audit.',
    timestamp: '4 hours ago',
    acknowledged: true,
    actionRequired: 'Dossier ready for download in Reports Hub',
  }
];

export const INITIAL_LOGS: StockLogEntry[] = [
  {
    id: 'log-01',
    timestamp: 'Today, 08:30 AM',
    medicineName: 'Amoxicillin Trihydrate 500mg',
    sku: 'SKU-AMOX-500',
    openingBalance: 625,
    intakeQty: 0,
    dispensedQty: 145,
    lossDamagedQty: 0,
    closingBalance: 480,
    loggedBy: 'Dr. Aris Thorne',
    status: 'Verified',
  },
  {
    id: 'log-02',
    timestamp: 'Today, 08:45 AM',
    medicineName: 'Ceftriaxone Sodium Inj 1g',
    sku: 'SKU-CEFT-1000',
    openingBalance: 252,
    intakeQty: 0,
    dispensedQty: 62,
    lossDamagedQty: 0,
    closingBalance: 190,
    loggedBy: 'Staff Pharmacist M. Patel',
    status: 'Verified',
  },
  {
    id: 'log-03',
    timestamp: 'Yesterday, 05:15 PM',
    medicineName: 'Paracetamol 650mg Tablets',
    sku: 'SKU-PARA-650',
    openingBalance: 10220,
    intakeQty: 5000,
    dispensedQty: 720,
    lossDamagedQty: 0,
    closingBalance: 14500,
    loggedBy: 'Dr. Aris Thorne',
    status: 'Verified',
  },
  {
    id: 'log-04',
    timestamp: 'Yesterday, 03:00 PM',
    medicineName: 'Metformin HCl 500mg',
    sku: 'SKU-METF-500',
    openingBalance: 2380,
    intakeQty: 0,
    dispensedQty: 280,
    lossDamagedQty: 0,
    closingBalance: 2100,
    loggedBy: 'Clinical Officer S. Rao',
    status: 'Verified',
  }
];

export const INITIAL_SYNC_BATCHES: ImportSyncBatch[] = [
  {
    id: 'SYNC-2026-901',
    source: 'DVDMS State Portal',
    timestamp: 'Today, 06:00 AM',
    recordsSynced: 1248,
    reconciledCount: 1234,
    flaggedDiscrepancies: 14,
    status: 'Completed',
  },
  {
    id: 'SYNC-2026-899',
    source: 'e-Aushadhi (National)',
    timestamp: 'Yesterday, 11:30 PM',
    recordsSynced: 1248,
    reconciledCount: 1248,
    flaggedDiscrepancies: 0,
    status: 'Completed',
  },
  {
    id: 'SYNC-2026-895',
    source: 'Manual CSV Intake',
    timestamp: 'Sept 20, 04:15 PM',
    recordsSynced: 350,
    reconciledCount: 348,
    flaggedDiscrepancies: 2,
    status: 'Completed',
  }
];
